#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# config/routes.yaml

# ...

admin:
  path: /admin
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: app_admin_home
    # make a permanent redirection...
    permanent: true
    # ...and keep the original query string parameters
    keepQueryParams: true

